<!doctype html>
<html lang="en" class="no-js">
<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<title>Limonade Starter Application</title>
	<meta name="description" content="">
	<meta name="author" content="">

	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<link rel="shortcut icon" href="/favicon.ico">
    <link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
	<link rel="stylesheet" href="css/style.css?v=2">
    <style type="text/css">
        .ajaxy {
            background: url(/images/ajax-loader.gif) left bottom no-repeat;
        }
    </style>

</head>
<body>
	<div id="container">
		<header>

		</header>

		<div id="main" role="main">

            <?= $content ?>

		</div>

		<footer>

		</footer>
	</div>

  <?= $js ?>

</body>
</html>
